server:
  servlet:
    context-path: /server
  port: 9090

spring:
  datasource:
    name: spring_boot_mybatis
    url: jdbc:mysql://47.98.144.216:3306/ivan_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid 数据源
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.98.144.216
    port: 6379
    password: yihao123

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.ivan.subproject.*.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

